package sip

import (
	"context"
	"log/slog"
	"strings"
	"sync"
	"time"
)

// rfc3261BranchCookie prefixes every branch parameter generated by an
// RFC 3261 compliant element (clause 8.1.1.7).
const rfc3261BranchCookie = "z9hG4bK"

// serverTransactionLifetime is how long a transaction is retained after its
// response, so that a retransmitted request can be answered from it rather
// than reprocessed. RFC 3261 Timer J, and Timer H for INVITE, are both
// 64*T1 = 32s on an unreliable transport.
var serverTransactionLifetime = 32 * time.Second

// transactionKey identifies a server transaction as described in RFC 3261
// clause 17.2.3: the branch parameter of the topmost Via, the sent-by value of
// that Via, and the method.
//
// ACK is keyed on its own method rather than folded onto the INVITE it
// acknowledges. That is a deliberate simplification: this table exists to
// absorb retransmissions, and an ACK never carries a response to replay.
type transactionKey struct {
	branch string
	sentBy string
	method string
}

type serverTransaction struct {
	mu       sync.Mutex
	response []byte
	at       time.Time
}

func (t *serverTransaction) storeResponse(resp []byte) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.response = append([]byte(nil), resp...)
	t.at = time.Now()
}

func (t *serverTransaction) lastResponse() []byte {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.response
}

func (t *serverTransaction) age(now time.Time) time.Duration {
	t.mu.Lock()
	defer t.mu.Unlock()
	return now.Sub(t.at)
}

// serverTransactionKey derives the transaction identity of an inbound request.
//
// It reports false when the topmost Via carries no RFC 3261 branch, because
// the RFC 2543 fallback matching rules compare the whole request and are not
// worth implementing for a peer that old. Such requests are processed without
// retransmission handling, exactly as before.
func serverTransactionKey(msg *Message) (transactionKey, bool) {
	// Parse fills Method from the first token of the start line, which for a
	// status line is "SIP/2.0". The request path already filters responses out,
	// but guard here too so the function is safe to call on any message.
	if strings.HasPrefix(strings.ToUpper(strings.TrimSpace(msg.StartLine)), "SIP/2.0 ") {
		return transactionKey{}, false
	}

	via := msg.Header("Via")
	if via == "" {
		return transactionKey{}, false
	}

	branch := viaParam(via, "branch")
	if !strings.HasPrefix(branch, rfc3261BranchCookie) {
		return transactionKey{}, false
	}

	method := strings.ToUpper(strings.TrimSpace(msg.Method))
	if method == "" {
		return transactionKey{}, false
	}
	return transactionKey{branch: branch, sentBy: viaSentBy(via), method: method}, true
}

// viaSentBy extracts the sent-by host and port from a Via value, which has the
// form "SIP/2.0/UDP host:port;param=value".
func viaSentBy(via string) string {
	value := via
	if i := strings.Index(value, ";"); i >= 0 {
		value = value[:i]
	}
	fields := strings.Fields(value)
	if len(fields) == 0 {
		return ""
	}
	return strings.TrimSpace(fields[len(fields)-1])
}

// viaParam returns a named parameter from a Via header value.
func viaParam(via, name string) string {
	for _, part := range strings.Split(via, ";")[1:] {
		part = strings.TrimSpace(part)
		key, value, found := strings.Cut(part, "=")
		if !found {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(key), name) {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

// beginServerTransaction admits a request for processing.
//
// It returns the responder the handler should use, and whether processing
// should continue. When the request is a retransmission of one already seen,
// the stored response is replayed and false is returned, so the handler never
// runs twice. Without this a duplicated INVITE re-created the dialog, re-wrote
// the call and re-sent every group notification.
func (s *Server) beginServerTransaction(msg *Message, send responder) (responder, bool) {
	key, ok := serverTransactionKey(msg)
	if !ok {
		return send, true
	}

	created := &serverTransaction{at: time.Now()}
	if existing, loaded := s.transactions.LoadOrStore(key, created); loaded {
		tx := existing.(*serverTransaction)
		if resp := tx.lastResponse(); len(resp) > 0 {
			if err := send(resp); err != nil {
				slog.Warn("SIP retransmission replay failed", "method", key.method, "branch", key.branch, "err", err)
			}
			slog.Debug("SIP retransmission answered from transaction",
				"method", key.method, "branch", key.branch, "sent_by", key.sentBy)
			return send, false
		}
		// Still being processed, and no response exists to replay. Absorbing it
		// is the right move: reprocessing would duplicate the side effects.
		slog.Debug("SIP retransmission absorbed while in progress",
			"method", key.method, "branch", key.branch, "sent_by", key.sentBy)
		return send, false
	}

	capture := func(resp []byte) error {
		created.storeResponse(resp)
		return send(resp)
	}
	return capture, true
}

// StartTransactionReaper removes transactions once they are older than
// serverTransactionLifetime. Without it the table grows for the life of the
// process, driven entirely by remote input.
func (s *Server) StartTransactionReaper(ctx context.Context) error {
	ticker := time.NewTicker(serverTransactionLifetime / 4)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil
		case <-ticker.C:
			s.reapTransactions(time.Now())
		}
	}
}

func (s *Server) reapTransactions(now time.Time) int {
	removed := 0
	s.transactions.Range(func(key, value any) bool {
		if value.(*serverTransaction).age(now) > serverTransactionLifetime {
			s.transactions.Delete(key)
			removed++
		}
		return true
	})
	if removed > 0 {
		slog.Debug("SIP transactions reaped", "count", removed)
	}
	return removed
}
